### ISSUE TITLE
Exception ao gerar boleto

### ISSUE THREAD

**Issue by mon1eiro** [weldonsouza/cielo_ecommerce#7]
```
I/flutter (22235): Operação por Boleto
I/flutter (22235): Gerando boleto....
E/flutter (22235): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: Class '_CastError' has no instance getter 'message'.
E/flutter (22235): Receiver: Instance of '_CastError'
E/flutter (22235): Tried calling: message
E/flutter (22235): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter (22235): #1      CieloEcommerce.createSale (package:cielo_ecommerce/src/cieloecommerce.dart:29:26)
E/flutter (22235): <asynchronous suspension>
E/flutter (22235): #2      Tentar.makePayment (package:loja_virtual/tentativa.dart:46:24)
E/flutter (22235): <asynchronous suspension>
```

**Comment by mon1eiro** [comment]
Voltou a funcionar do nada
